import type { Metadata } from "next";
import {
  Playfair_Display,
  Oswald,
  Cuprum,
  Domine,
  Cedarville_Cursive,
} from "next/font/google";
import "./globals.css";

const poynter = Playfair_Display({ subsets: ["latin"], variable: "--poynter" });
const cervo = Oswald({ subsets: ["latin"], variable: "--cervo" });
const brandon = Cuprum({ subsets: ["latin"], variable: "--brandon" });
const sentinel = Domine({ subsets: ["latin"], variable: "--sentinel" });
const signature = Cedarville_Cursive({
  subsets: ["latin"],
  variable: "--signature",
  weight: "400",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${poynter.variable} ${cervo.variable} ${brandon.variable} ${sentinel.variable} ${signature.variable}`}
    >
      <body className={"bg-brand-pink-200"}>{children}</body>
    </html>
  );
}
